#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Write provenance-rich meta.json for mesh runs (schema_version=1).

This is intended to support "paper-grade" reproducibility:
  - Record versions/environment
  - Archive local_run_config.json (and optionally BCSR meta files) into run_dir/inputs/
  - Record sha256 for archived inputs

Note: essential_summary_mesh.json is generated by compute_essential_summary_mesh.py.
This tool focuses on provenance and should be invoked before computing summary.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional


def _read_json(path: Path) -> Dict[str, Any]:
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        while True:
            chunk = f.read(1024 * 1024)
            if not chunk:
                break
            h.update(chunk)
    return h.hexdigest()


def _copy2(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(src, dst)


def _run_capture(cmd: List[str]) -> str:
    try:
        p = subprocess.run(cmd, text=True, capture_output=True, check=False)
        out = (p.stdout or "").strip()
        err = (p.stderr or "").strip()
        if out:
            return out
        if err:
            return err
        return ""
    except Exception:
        return ""


def _infer_bcsr_root(project_root: Path) -> Optional[Path]:
    def _valid(root: Path) -> bool:
        return (root / "pe00" / "core00.bcsr.bin.meta.json").exists()

    # Explicit env override wins.
    bcsr_env = os.environ.get("MESH_BCSR_DIR", "").strip()
    if bcsr_env:
        p = Path(bcsr_env).expanduser().resolve()
        if _valid(p):
            return p

    weights_dir = project_root / "weights"
    cand10 = weights_dir / "bcsr_global_16pe_fanout256_10k"
    cand100 = weights_dir / "bcsr_global_16pe_fanout256"
    if _valid(cand10):
        return cand10
    if _valid(cand100):
        return cand100
    for mp in sorted(weights_dir.glob("*/pe00/core00.bcsr.bin.meta.json")):
        root = mp.parent.parent
        if _valid(root):
            return root
    return None


def _resolve_path_under_project(project_root: Path, raw_path: str) -> str:
    p = (raw_path or "").strip()
    if not p:
        return ""
    if os.path.isabs(p):
        return p
    # Most mesh runners `cd sst_dram_si/` before invoking SST; tolerate both:
    # - "configs/ramulator2_ddr4_openrow.cfg"
    # - "sst_dram_si/configs/ramulator2_ddr4_openrow.cfg"
    if p.startswith("sst_dram_si/"):
        p = p[len("sst_dram_si/"):]
    return str((project_root / p).resolve())


def _archive_local_run_config(project_root: Path, run_dir: Path) -> Optional[Dict[str, Any]]:
    src = project_root / "local_run_config.json"
    if not src.exists():
        return None

    # Keep backwards compatibility: compute_essential_summary_mesh.py expects this at run root.
    _copy2(src, run_dir / "local_run_config.json")

    dst = run_dir / "inputs" / "local_run_config.json"
    _copy2(src, dst)
    return {
        "path": str(dst.relative_to(run_dir)),
        "sha256": _sha256_file(dst),
        "bytes": int(dst.stat().st_size),
    }

def _archive_spec_json(spec_path: Path, run_dir: Path) -> Optional[Dict[str, Any]]:
    if not spec_path.exists():
        return None
    dst = run_dir / "inputs" / "spec.json"
    _copy2(spec_path, dst)
    return {
        "path": str(dst.relative_to(run_dir)),
        "sha256": _sha256_file(dst),
        "bytes": int(dst.stat().st_size),
    }


def _archive_bcsr_meta_files(bcsr_root: Path, run_dir: Path) -> Dict[str, Any]:
    metas = sorted(bcsr_root.glob("pe*/core*.bcsr.bin.meta.json"))
    dst_root = run_dir / "inputs" / "bcsr_meta"
    out_files: List[Dict[str, Any]] = []
    for mp in metas:
        rel = mp.relative_to(bcsr_root)
        dst = dst_root / rel
        _copy2(mp, dst)
        out_files.append(
            {
                "path": str(dst.relative_to(run_dir)),
                "sha256": _sha256_file(dst),
                "bytes": int(dst.stat().st_size),
            }
        )
    return {
        "dataset_root": str(bcsr_root),
        "meta_files": out_files,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--run-dir", required=True, help="run directory (will write meta.json)")
    ap.add_argument("--project-root", required=True, help="sst_dram_si project root")
    ap.add_argument("--sst-bin", required=True, help="path to sst binary")
    ap.add_argument("--model", required=True, help="path to sst python model script")
    ap.add_argument("--sst-nproc", type=int, default=32, help="sst -n <N> value (recorded for provenance)")
    args = ap.parse_args()

    run_dir = Path(args.run_dir).resolve()
    project_root = Path(args.project_root).resolve()
    sst_bin = Path(args.sst_bin).resolve()
    model = Path(args.model).resolve()
    run_dir.mkdir(parents=True, exist_ok=True)
    (run_dir / "inputs").mkdir(parents=True, exist_ok=True)

    spec_path_raw = (os.environ.get("MESH_SPEC_JSON") or "").strip()
    spec_first = bool(spec_path_raw)
    state: Dict[str, Any] = {}

    spec_input: Optional[Dict[str, Any]] = None
    if spec_first:
        spec_path = Path(spec_path_raw).expanduser().resolve()
        spec_input = _archive_spec_json(spec_path, run_dir) if spec_path.exists() else None
        try:
            # Resolve spec -> legacy state (single source of truth for spec-first runs).
            sys.path.insert(0, str(project_root))
            from mesh_template.legacy_defaults import make_default_state  # type: ignore
            from mesh_template.spec import load_spec as _load_spec  # type: ignore
            from mesh_template.spec import resolve_spec as _resolve_spec  # type: ignore

            resolved = _resolve_spec(_load_spec(str(spec_path)), defaults_state=make_default_state())
            st_any = resolved.get("state") if isinstance(resolved, dict) else {}
            state = dict(st_any or {}) if isinstance(st_any, dict) else {}
        except Exception:
            state = {}

    cfg_input = _archive_local_run_config(project_root, run_dir) if not spec_first else None
    cfg = _read_json(run_dir / "local_run_config.json") if (run_dir / "local_run_config.json").exists() else {}

    if spec_first:
        mesh_size = int(state.get("MESH_SIZE", 4) or 4)
        node_limit_raw = int(state.get("SPEC_NODE_LIMIT", 0) or 0)
        num_cores = int(state.get("NUM_CORES_PER_PE", 4) or 4)
        neurons_per_core = int(state.get("NEURONS_PER_CORE", 4) or 4)
    else:
        mesh_size = int(cfg.get("mesh_size", 4))
        node_limit_raw = int(cfg.get("node_limit", 0) or 0)
        num_cores = int(cfg.get("num_cores_per_pe", 20))
        neurons_per_core = int(cfg.get("neurons_per_core", 500))

    total_pes = int(mesh_size * mesh_size)
    if node_limit_raw > 0:
        num_pes = max(1, min(int(node_limit_raw), total_pes))
    else:
        num_pes = total_pes

    # If BCSR is enabled, prefer rows from the weight meta file (prevents mismatch with config).
    bcsr_section: Optional[Dict[str, Any]] = None
    bcsr_meta_path = None
    rows_from_bcsr = None
    use_bcsr = bool(int((state.get("STEP_ACTIVATION_USE_BCSR_ROUTES", 0) if spec_first else cfg.get("step_activation_use_bcsr_routes", 0)) or 0))
    if use_bcsr:
        bcsr_root = _infer_bcsr_root(project_root)
        if bcsr_root is not None:
            mp = bcsr_root / "pe00" / "core00.bcsr.bin.meta.json"
            if mp.exists():
                bcsr_meta_path = str(mp)
                meta0 = _read_json(mp)
                rows = int(meta0.get("rows", 0) or 0)
                if rows > 0:
                    rows_from_bcsr = rows
                    neurons_per_core = rows
            bcsr_section = _archive_bcsr_meta_files(bcsr_root, run_dir)

    neurons_per_pe = int(num_cores) * int(neurons_per_core)

    # Resolved runtime "mode" knobs (even if env vars are unset).
    exec_mode = (str(state.get("SPEC_EXEC_MODE", "")) if spec_first else (os.environ.get("MESH_EXEC_MODE") or "")).strip().lower() or "gas"
    workload_impl = (str(state.get("SPEC_WORKLOAD_IMPL", "")) if spec_first else (os.environ.get("SNNDL_WORKLOAD_IMPL") or "")).strip().lower() or "snn"
    sim_time = str(state.get("SIMULATION_TIME", "200us") if spec_first else cfg.get("sim_time", "100us"))
    sim_time_override = (os.environ.get("MESH_SIM_TIME") or "").strip()
    exp_profile = (os.environ.get("MESH_EXPERIMENT_PROFILE") or "").strip()
    if not exp_profile:
        exp_profile = str(cfg.get("experiment_profile", "") or "").strip()
    max_steps_env = (os.environ.get("MESH_MAX_STEPS") or "").strip()
    max_steps: Optional[int] = None
    if spec_first:
        try:
            max_steps = int(state.get("SPEC_MAX_STEPS", 0) or 0)
        except Exception:
            max_steps = 0
        if max_steps <= 0:
            max_steps = None
    elif max_steps_env:
        try:
            max_steps = int(max_steps_env)
        except Exception:
            max_steps = None

    model_meta: Dict[str, Any] = {
        "mesh_size": mesh_size,
        "node_limit": int(node_limit_raw),
        "num_pes": int(num_pes),
        "num_cores_per_pe": int(num_cores),
        "neurons_per_core": int(neurons_per_core),
        "neurons_per_pe": int(neurons_per_pe),
        "sim_time": sim_time,
        "exec_mode": exec_mode,
        "workload_impl": workload_impl,
    }
    if spec_first:
        model_meta["spec_first"] = 1
        model_meta["line_size_bytes"] = int(state.get("SUBCOMP_LINE_BYTES", 64) or 64)
        model_meta["loader_chunk_bytes"] = int(state.get("LOADER_CHUNK_BYTES", 64) or 64)
        model_meta["global_step_sync_enable"] = int(1 if bool(state.get("GLOBAL_STEP_SYNC_ENABLE", False)) else 0)
        model_meta["step_activation_fraction"] = float(state.get("STEP_ACTIVATION_FRACTION", 0.0) or 0.0)
        model_meta["step_activation_fanout"] = int(state.get("STEP_ACTIVATION_FANOUT", 0) or 0)
        model_meta["step_activation_seed"] = int(state.get("STEP_ACTIVATION_SEED", 0) or 0)
        model_meta["step_activation_event_weight"] = float(state.get("STEP_ACTIVATION_EVENT_WEIGHT", 0.0) or 0.0)
        model_meta["step_reset_mem_each_step"] = int(state.get("STEP_RESET_MEM_EACH_STEP", 0) or 0)
    if exp_profile:
        model_meta["experiment_profile"] = exp_profile
    # Memory backend (MemController backend). Prefer env overrides for experiment runs.
    mem_backend_raw = (
        str(state.get("MEM_BACKEND", "")) if spec_first else (os.environ.get("MESH_MEM_BACKEND") or cfg.get("mem_backend") or "")
    ).strip().lower()
    mem_backend = mem_backend_raw or "simple"
    if mem_backend in ("simplemem", "simple_mem"):
        mem_backend = "simple"
    if mem_backend in ("ram2",):
        mem_backend = "ramulator2"
    model_meta["mem_backend"] = mem_backend
    if mem_backend == "ramulator2":
        r2 = (
            str(state.get("RAMULATOR2_CONFIG_FILE", "")) if spec_first else (os.environ.get("MESH_RAMULATOR2_CONFIG_FILE") or cfg.get("ramulator2_config_file") or "")
        ).strip()
        if r2:
            model_meta["ramulator2_config_file"] = _resolve_path_under_project(project_root, r2)
    smat = (
        str(state.get("SIMPLEMEM_ACCESS_TIME", "")) if spec_first else (os.environ.get("MESH_SIMPLEMEM_ACCESS_TIME") or cfg.get("simplemem_access_time") or "")
    ).strip()
    if smat:
        model_meta["simplemem_access_time"] = smat

    # Record effective step activation knobs (env overrides > local_run_config.json).
    # This is consumed by compute_essential_summary_mesh.py to avoid "config drift" during sweeps.
    if not spec_first:
        _frac_env = (os.environ.get("MESH_STEP_ACTIVATION_FRACTION") or "").strip()
        if _frac_env:
            try:
                model_meta["step_activation_fraction"] = float(_frac_env)
            except Exception:
                model_meta["step_activation_fraction_raw"] = _frac_env
        elif cfg.get("step_activation_fraction") is not None:
            try:
                model_meta["step_activation_fraction"] = float(cfg.get("step_activation_fraction"))
            except Exception:
                pass

        _fan_env = (os.environ.get("MESH_STEP_ACTIVATION_FANOUT") or "").strip()
        if _fan_env:
            try:
                model_meta["step_activation_fanout"] = int(_fan_env)
            except Exception:
                model_meta["step_activation_fanout_raw"] = _fan_env
        elif cfg.get("step_activation_fanout") is not None:
            try:
                model_meta["step_activation_fanout"] = int(cfg.get("step_activation_fanout"))
            except Exception:
                pass

        _seed_env = (os.environ.get("MESH_STEP_ACTIVATION_SEED") or "").strip()
        if _seed_env:
            try:
                model_meta["step_activation_seed"] = int(_seed_env)
            except Exception:
                model_meta["step_activation_seed_raw"] = _seed_env
        elif cfg.get("step_activation_seed") is not None:
            try:
                model_meta["step_activation_seed"] = int(cfg.get("step_activation_seed"))
            except Exception:
                pass

        _ew_env = (os.environ.get("MESH_STEP_ACTIVATION_EVENT_WEIGHT") or "").strip()
        if _ew_env:
            try:
                model_meta["step_activation_event_weight"] = float(_ew_env)
            except Exception:
                model_meta["step_activation_event_weight_raw"] = _ew_env
        elif cfg.get("step_activation_event_weight") is not None:
            try:
                model_meta["step_activation_event_weight"] = float(cfg.get("step_activation_event_weight"))
            except Exception:
                pass

        _pp_env = (os.environ.get("MESH_STEP_ACTIVATION_PRE_PATTERN") or "").strip()
        if _pp_env:
            model_meta["step_activation_pre_pattern"] = _pp_env.strip().lower()
        elif cfg.get("step_activation_pre_pattern") is not None:
            try:
                model_meta["step_activation_pre_pattern"] = str(cfg.get("step_activation_pre_pattern") or "").strip().lower()
            except Exception:
                pass

        _pcl_env = (os.environ.get("MESH_STEP_ACTIVATION_PRE_CLUSTER_LEN") or "").strip()
        if _pcl_env:
            try:
                model_meta["step_activation_pre_cluster_len"] = int(_pcl_env)
            except Exception:
                model_meta["step_activation_pre_cluster_len_raw"] = _pcl_env
        elif cfg.get("step_activation_pre_cluster_len") is not None:
            try:
                model_meta["step_activation_pre_cluster_len"] = int(cfg.get("step_activation_pre_cluster_len"))
            except Exception:
                pass

        _reset_env = (os.environ.get("MESH_STEP_RESET_MEM_EACH_STEP") or "").strip().lower()
        if _reset_env:
            if _reset_env in ("1", "true", "yes", "y", "on"):
                model_meta["step_reset_mem_each_step"] = 1
            elif _reset_env in ("0", "false", "no", "n", "off"):
                model_meta["step_reset_mem_each_step"] = 0
            else:
                model_meta["step_reset_mem_each_step_raw"] = _reset_env
        elif cfg.get("step_reset_mem_each_step") is not None:
            try:
                model_meta["step_reset_mem_each_step"] = int(1 if bool(cfg.get("step_reset_mem_each_step")) else 0)
            except Exception:
                pass

    # Allow long runs to have neurons_fired_total=0 (e.g. "freeze dynamics" experiments).
    # Record it here so validate_essential_summary_mesh.py can skip the non-zero-firing gate.
    _az_env = (os.environ.get("MESH_ALLOW_ZERO_FIRING_LONG") or "").strip().lower()
    allow_zero_long: Optional[bool] = None
    if _az_env:
        allow_zero_long = _az_env in ("1", "true", "yes", "y", "on")
    elif "allow_zero_firing_long" in cfg:
        try:
            allow_zero_long = bool(cfg.get("allow_zero_firing_long"))
        except Exception:
            allow_zero_long = None
    if allow_zero_long is not None:
        model_meta["allow_zero_firing_long"] = int(1 if allow_zero_long else 0)

    # Strict-step gating for GAS (paper fairness experiments):
    # - Keeps MESH_EXEC_MODE=gas (core assembly remains GAS)
    # - Enables step_seq tagging+gating at the PE boundary to disable within-step cascading
    _gate_env = (os.environ.get("MESH_GAS_STEP_SEQ_GATE_ENABLE") or "").strip().lower()
    if _gate_env:
        model_meta["gas_step_seq_gate_enable"] = int(1 if _gate_env in ("1", "true", "yes", "y", "on") else 0)

    _force_defer_env = (os.environ.get("MESH_GAS_FORCE_DEFER") or "").strip().lower()
    if _force_defer_env:
        model_meta["gas_force_defer"] = int(1 if _force_defer_env in ("1", "true", "yes", "y", "on") else 0)

    # Record effective GAS merge knobs (env overrides > local_run_config.json).
    # Rationale: most matrix scripts DO NOT mutate local_run_config.json; without recording the override here,
    # analysts may misread results (e.g., calibration sweeps across memory backends).
    def _maybe_record_int(key_out: str, env_key: str, cfg_key: str) -> None:
        raw = (os.environ.get(env_key) or "").strip()
        if raw:
            try:
                model_meta[key_out] = int(raw)
            except Exception:
                model_meta[f"{key_out}_raw"] = raw
            return
        if cfg.get(cfg_key) is not None:
            try:
                model_meta[key_out] = int(cfg.get(cfg_key))
            except Exception:
                pass

    def _maybe_record_str(key_out: str, env_key: str, cfg_key: str) -> None:
        raw = (os.environ.get(env_key) or "").strip()
        if raw:
            model_meta[key_out] = raw
            return
        if cfg.get(cfg_key) is not None:
            try:
                model_meta[key_out] = str(cfg.get(cfg_key) or "").strip()
            except Exception:
                pass

    # Merge policy itself is config-defined; still record it for reproducibility.
    if spec_first:
        model_meta["gas_merge_policy"] = str(state.get("_GAS_MERGE_POLICY", "") or "").strip()
        model_meta["gap_merge_k_bytes"] = int(state.get("_GAS_GAP_K_BYTES", 0) or 0)
        model_meta["burst_bytes_max"] = int(state.get("_GAS_LMAX_BYTES", 0) or 0)
        model_meta["row_window_bytes"] = int(state.get("_GAS_ROW_WINDOW_BYTES", 0) or 0)
        model_meta["row_window_timeout_ns"] = int(state.get("_GAS_ROW_WINDOW_TIMEOUT_NS", 0) or 0)
        model_meta["gas_sort_policy"] = str(state.get("_GAS_SORT_POLICY", "") or "").strip()
        model_meta["gas_row_bytes_guess"] = int(state.get("_GAS_ROW_BYTES_GUESS", 0) or 0)
        model_meta["gas_bank_bits"] = int(state.get("_GAS_BANK_BITS", 0) or 0)
        model_meta["gas_bank_shift"] = int(state.get("_GAS_BANK_SHIFT", 0) or 0)
        model_meta["gas_bank_auto_enable"] = int(state.get("_GAS_BANK_AUTO_ENABLE", 0) or 0)
    else:
        if cfg.get("gas_merge_policy") is not None:
            try:
                model_meta["gas_merge_policy"] = str(cfg.get("gas_merge_policy") or "").strip()
            except Exception:
                pass
        _maybe_record_int("gap_merge_k_bytes", "MESH_GAS_GAP_K_BYTES", "gap_merge_k_bytes")
        _maybe_record_int("burst_bytes_max", "MESH_GAS_LMAX_BYTES", "burst_bytes_max")
        _maybe_record_int("row_window_bytes", "MESH_GAS_ROW_WINDOW_BYTES", "row_window_bytes")
        _maybe_record_int("row_window_timeout_ns", "MESH_GAS_ROW_WINDOW_TIMEOUT_NS", "row_window_timeout_ns")
        _maybe_record_str("gas_sort_policy", "MESH_GAS_SORT_POLICY", "gas_sort_policy")
        _maybe_record_int("gas_row_bytes_guess", "MESH_GAS_ROW_BYTES_GUESS", "gas_row_bytes_guess")
        _maybe_record_int("gas_bank_bits", "MESH_GAS_BANK_BITS", "gas_bank_bits")
        _maybe_record_int("gas_bank_shift", "MESH_GAS_BANK_SHIFT", "gas_bank_shift")
        _maybe_record_int("gas_bank_auto_enable", "MESH_GAS_BANK_AUTO_ENABLE", "gas_bank_auto_enable")

    # Record effective L1 enable (env overrides > config). This avoids mutating local_run_config.json
    # between experiment runs when sweeping cache on/off.
    if spec_first:
        model_meta["l1_enable"] = int(1 if bool(state.get("L1_ENABLE", False)) else 0)
    else:
        _l1_env = (os.environ.get("MESH_L1_ENABLE") or "").strip().lower()
        l1_enable: Optional[bool] = None
        if _l1_env:
            if _l1_env in ("1", "true", "yes", "y", "on"):
                l1_enable = True
            elif _l1_env in ("0", "false", "no", "n", "off"):
                l1_enable = False
            else:
                model_meta["l1_enable_raw"] = _l1_env
        elif "l1_enable" in cfg:
            try:
                l1_enable = bool(cfg.get("l1_enable"))
            except Exception:
                l1_enable = None
        if l1_enable is not None:
            model_meta["l1_enable"] = int(1 if l1_enable else 0)
    if sim_time_override:
        model_meta["sim_time_override"] = sim_time_override
    if max_steps is not None:
        model_meta["max_steps"] = int(max_steps)
    if bcsr_meta_path:
        model_meta["bcsr_meta_path"] = bcsr_meta_path
    if rows_from_bcsr is not None:
        model_meta["bcsr_rows_override"] = int(rows_from_bcsr)

    compare_role = (os.environ.get("MESH_COMPARE_ROLE") or "").strip().lower()
    if compare_role:
        model_meta["compare_role"] = compare_role

    requested_exec_mode = (os.environ.get("MESH_COMPARE_REQUESTED_EXEC_MODE") or "").strip().lower()
    if requested_exec_mode:
        model_meta["requested_exec_mode"] = requested_exec_mode

    effective_exec_mode = (os.environ.get("MESH_COMPARE_EFFECTIVE_EXEC_MODE") or "").strip().lower()
    if effective_exec_mode:
        model_meta["effective_exec_mode"] = effective_exec_mode
    elif compare_role or requested_exec_mode:
        model_meta["effective_exec_mode"] = exec_mode

    bounded_validation_raw = (os.environ.get("MESH_COMPARE_BOUNDED_VALIDATION") or "").strip().lower()
    if bounded_validation_raw:
        if bounded_validation_raw in ("1", "true", "yes", "y", "on"):
            model_meta["bounded_validation"] = 1
        elif bounded_validation_raw in ("0", "false", "no", "n", "off"):
            model_meta["bounded_validation"] = 0
        else:
            model_meta["bounded_validation_raw"] = bounded_validation_raw

    # Versions
    sst_ver = _run_capture([str(sst_bin), "--version"])
    if sst_ver:
        # Normalize to a single line (validator only needs a stable string).
        sst_ver = sst_ver.splitlines()[0].strip()

    meta: Dict[str, Any] = {
        "schema_version": 1,
        "run": {
            "run_id": run_dir.name,
            "created_utc": datetime.now(timezone.utc).isoformat(),
            "hostname": platform.node(),
        },
        "command": {
            "sst_bin": str(sst_bin),
            "sst_args": ["-n", str(int(args.sst_nproc)), str(model)],
            "model_script_path": str(model),
        },
        "versions": {
            "sst_version": sst_ver or "",
            "python_version": platform.python_version(),
        },
        "environment": {
            "SNNDL_WORKLOAD_IMPL": os.environ.get("SNNDL_WORKLOAD_IMPL", ""),
            "MESH_EXEC_MODE": os.environ.get("MESH_EXEC_MODE", ""),
            "MESH_SIM_TIME": os.environ.get("MESH_SIM_TIME", ""),
            "MESH_BCSR_DIR": os.environ.get("MESH_BCSR_DIR", ""),
            "MESH_BCSR_BLOCK_FETCH_MODE": os.environ.get("MESH_BCSR_BLOCK_FETCH_MODE", ""),
            "MESH_BCSR_LAYOUT_MODE": os.environ.get("MESH_BCSR_LAYOUT_MODE", ""),
            "MESH_GAS_STEP_SEQ_GATE_ENABLE": os.environ.get("MESH_GAS_STEP_SEQ_GATE_ENABLE", ""),
            "MESH_GAS_FORCE_DEFER": os.environ.get("MESH_GAS_FORCE_DEFER", ""),
            "MESH_GAS_SORT_POLICY": os.environ.get("MESH_GAS_SORT_POLICY", ""),
            "MESH_GAS_ROW_BYTES_GUESS": os.environ.get("MESH_GAS_ROW_BYTES_GUESS", ""),
            "MESH_GAS_BANK_BITS": os.environ.get("MESH_GAS_BANK_BITS", ""),
            "MESH_GAS_BANK_SHIFT": os.environ.get("MESH_GAS_BANK_SHIFT", ""),
            "MESH_GAS_BANK_AUTO_ENABLE": os.environ.get("MESH_GAS_BANK_AUTO_ENABLE", ""),
            "MESH_FREEZE_READONLY": os.environ.get("MESH_FREEZE_READONLY", ""),
            "MESH_READONLY_V_THRESH": os.environ.get("MESH_READONLY_V_THRESH", ""),
            "MESH_READONLY_TAU_MEM": os.environ.get("MESH_READONLY_TAU_MEM", ""),
            "MESH_L1_ENABLE": os.environ.get("MESH_L1_ENABLE", ""),
            "MESH_STEP_ACTIVATION_FRACTION": os.environ.get("MESH_STEP_ACTIVATION_FRACTION", ""),
            "MESH_STEP_ACTIVATION_FANOUT": os.environ.get("MESH_STEP_ACTIVATION_FANOUT", ""),
            "MESH_STEP_ACTIVATION_SEED": os.environ.get("MESH_STEP_ACTIVATION_SEED", ""),
            "MESH_STEP_ACTIVATION_EVENT_WEIGHT": os.environ.get("MESH_STEP_ACTIVATION_EVENT_WEIGHT", ""),
            "MESH_STEP_ACTIVATION_PRE_PATTERN": os.environ.get("MESH_STEP_ACTIVATION_PRE_PATTERN", ""),
            "MESH_STEP_ACTIVATION_PRE_CLUSTER_LEN": os.environ.get("MESH_STEP_ACTIVATION_PRE_CLUSTER_LEN", ""),
            "MESH_STEP_RESET_MEM_EACH_STEP": os.environ.get("MESH_STEP_RESET_MEM_EACH_STEP", ""),
            "MESH_ALLOW_ZERO_FIRING_LONG": os.environ.get("MESH_ALLOW_ZERO_FIRING_LONG", ""),
            "SST_INSTALL_PREFIX": os.environ.get("SST_INSTALL_PREFIX", ""),
            "MESH_MAX_STEPS": os.environ.get("MESH_MAX_STEPS", ""),
            "MESH_EXPERIMENT_PROFILE": os.environ.get("MESH_EXPERIMENT_PROFILE", ""),
            "MESH_SPEC_JSON": os.environ.get("MESH_SPEC_JSON", ""),
            "MESH_COMPARE_ROLE": os.environ.get("MESH_COMPARE_ROLE", ""),
            "MESH_COMPARE_REQUESTED_EXEC_MODE": os.environ.get("MESH_COMPARE_REQUESTED_EXEC_MODE", ""),
            "MESH_COMPARE_EFFECTIVE_EXEC_MODE": os.environ.get("MESH_COMPARE_EFFECTIVE_EXEC_MODE", ""),
            "MESH_COMPARE_BOUNDED_VALIDATION": os.environ.get("MESH_COMPARE_BOUNDED_VALIDATION", ""),
        },
        "inputs": {},
        "model": model_meta,
    }

    if cfg_input is not None:
        meta["inputs"]["local_run_config"] = cfg_input
    if spec_input is not None:
        meta["inputs"]["spec"] = spec_input
    if bcsr_section is not None:
        meta["inputs"]["bcsr"] = bcsr_section

    out_path = run_dir / "meta.json"
    out_path.write_text(json.dumps(meta, indent=2, ensure_ascii=False), encoding="utf-8")
    print(f"[meta] written: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
